linters:
  enable-all: true
  disable:
    - deadcode
    - scopelint
    - maligned
    - interfacer
    - exhaustivestruct
    - nosnakecase
    - varcheck
    - structcheck
    - ifshort
    - golint

    - cyclop
    - depguard                  # TODO
    - forbidigo
    - funlen
    - gocyclo
    - godox                     # I'll have as many TODOs as I like.
    - gomnd
    - lll
    - nlreturn
    - varnamelen
    - whitespace
    - wsl
    
issues:
  exclude-files:
    - opcodes.go
