linters:
  enable-all: true
  disable:
    - deadcode
    - execinquery
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    #
    - cyclop
    - depguard                  # TODO
    - dupword
    - forbidigo
    - funlen
    - gocyclo
    - godox            # thanks, but i'll have as many todos as i like
    - gomnd
    - ineffassign               # esp gets updated for clarity
    - lll
    - mnd
    - nlreturn
    - varnamelen
    - wastedassign              # esp gets updated for clarity
    - whitespace
    - wsl
